version: 2
updates:
  # Configuration for Go
  - package-ecosystem: "gomod"
    directory: "/webserver"
    schedule:
      interval: "daily"
    pull-request-branch-name:
      separator: "_"
  # Configuration for Dockerfile
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    pull-request-branch-name:
      separator: "_"
  # Configuration for Python (functional and e2e tests)
  - package-ecosystem: "pip"
    directory: "/test"
    schedule:
      interval: "daily"
    pull-request-branch-name:
      separator: "_"
