version: "3.2"

services:
  webserver:
    container_name: webserver
    image: webserver
    build:
      context: ./webserver
    command: go run ./main
    volumes:
      - ./webserver/main:/app/main
    ports:
      - "8080:8080"

  python_tests:
    container_name: python_tests
    image: python_tests
    build:
      context: ./test
    volumes:
      - ./test:/app
