version: "3.8"

services:
  webserver:
    container_name: webserver
    image: webserver
    build:
      context: .
    command: go run .
    # volumes:
    #   - .:/app
    ports:
      - "8080:8080"
