# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/crypto.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12proto/crypto.proto\x12\x13go_webserver.crypto\"<\n\x0e\x45ncryptRequest\x12\x0f\n\x07\x63ontext\x18\x01 \x01(\t\x12\x19\n\x11unencrypted_value\x18\x02 \x01(\x0c\"*\n\x0f\x45ncryptResponse\x12\x17\n\x0f\x65ncrypted_value\x18\x01 \x01(\x0c\":\n\x0e\x44\x65\x63ryptRequest\x12\x0f\n\x07\x63ontext\x18\x01 \x01(\t\x12\x17\n\x0f\x65ncrypted_value\x18\x02 \x01(\x0c\"*\n\x0f\x44\x65\x63ryptResponse\x12\x17\n\x0f\x64\x65\x63rypted_value\x18\x01 \x01(\x0c\x32\xb8\x01\n\x06\x43rypto\x12V\n\x07\x45ncrypt\x12#.go_webserver.crypto.EncryptRequest\x1a$.go_webserver.crypto.EncryptResponse\"\x00\x12V\n\x07\x44\x65\x63rypt\x12#.go_webserver.crypto.DecryptRequest\x1a$.go_webserver.crypto.DecryptResponse\"\x00\x42\x32Z0github.com/afaguilarr/go-example-webserver/protob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.crypto_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z0github.com/afaguilarr/go-example-webserver/proto'
  _ENCRYPTREQUEST._serialized_start=43
  _ENCRYPTREQUEST._serialized_end=103
  _ENCRYPTRESPONSE._serialized_start=105
  _ENCRYPTRESPONSE._serialized_end=147
  _DECRYPTREQUEST._serialized_start=149
  _DECRYPTREQUEST._serialized_end=207
  _DECRYPTRESPONSE._serialized_start=209
  _DECRYPTRESPONSE._serialized_end=251
  _CRYPTO._serialized_start=254
  _CRYPTO._serialized_end=438
# @@protoc_insertion_point(module_scope)
