# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/users.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
from proto import common_pb2 as proto_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11proto/users.proto\x12\x12go_webserver.users\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x12proto/common.proto\"\xbc\x01\n\x08UserInfo\x12:\n\x0fpet_master_info\x18\x01 \x01(\x0b\x32!.go_webserver.users.PetMasterInfo\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x31\n\x0b\x64\x65scription\x18\x03 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12/\n\x0bprofile_pic\x18\x04 \x01(\x0b\x32\x1a.go_webserver.common.Image\"\x83\x01\n\rPetMasterInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x34\n\x0e\x63ontact_number\x18\x02 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12.\n\x08location\x18\x03 \x01(\x0b\x32\x1c.go_webserver.users.Location\"\xf4\x01\n\x08Location\x12\x0f\n\x07\x63ountry\x18\x01 \x01(\t\x12\x37\n\x11state_or_province\x18\x02 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12:\n\x14\x63ity_or_municipality\x18\x03 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12\x32\n\x0cneighborhood\x18\x04 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12.\n\x08zip_code\x18\x05 \x01(\x0b\x32\x1c.google.protobuf.StringValue\"T\n\x0fRegisterRequest\x12/\n\tuser_info\x18\x01 \x01(\x0b\x32\x1c.go_webserver.users.UserInfo\x12\x10\n\x08password\x18\x02 \x01(\t\"C\n\x10RegisterResponse\x12/\n\tuser_info\x18\x01 \x01(\x0b\x32\x1c.go_webserver.users.UserInfo2`\n\x05Users\x12W\n\x08Register\x12#.go_webserver.users.RegisterRequest\x1a$.go_webserver.users.RegisterResponse\"\x00\x42\x32Z0github.com/afaguilarr/go-example-webserver/protob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.users_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z0github.com/afaguilarr/go-example-webserver/proto'
  _USERINFO._serialized_start=94
  _USERINFO._serialized_end=282
  _PETMASTERINFO._serialized_start=285
  _PETMASTERINFO._serialized_end=416
  _LOCATION._serialized_start=419
  _LOCATION._serialized_end=663
  _REGISTERREQUEST._serialized_start=665
  _REGISTERREQUEST._serialized_end=749
  _REGISTERRESPONSE._serialized_start=751
  _REGISTERRESPONSE._serialized_end=818
  _USERS._serialized_start=820
  _USERS._serialized_end=916
# @@protoc_insertion_point(module_scope)
