# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import crypto_pb2 as proto_dot_crypto__pb2


class CryptoStub(object):
    """Crypto exposes all the necessary RPCs to Encrypt or Decrypt information.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Encrypt = channel.unary_unary(
                '/go_webserver.crypto.Crypto/Encrypt',
                request_serializer=proto_dot_crypto__pb2.EncryptRequest.SerializeToString,
                response_deserializer=proto_dot_crypto__pb2.EncryptResponse.FromString,
                )
        self.Decrypt = channel.unary_unary(
                '/go_webserver.crypto.Crypto/Decrypt',
                request_serializer=proto_dot_crypto__pb2.DecryptRequest.SerializeToString,
                response_deserializer=proto_dot_crypto__pb2.DecryptResponse.FromString,
                )


class CryptoServicer(object):
    """Crypto exposes all the necessary RPCs to Encrypt or Decrypt information.
    """

    def Encrypt(self, request, context):
        """Encrypt receives a strings for a context and an unencrypted value, and returns an encrypted value
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Decrypt(self, request, context):
        """Decrypt receives a strings for a context and an encrypted value, and returns a dencrypted value
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CryptoServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Encrypt': grpc.unary_unary_rpc_method_handler(
                    servicer.Encrypt,
                    request_deserializer=proto_dot_crypto__pb2.EncryptRequest.FromString,
                    response_serializer=proto_dot_crypto__pb2.EncryptResponse.SerializeToString,
            ),
            'Decrypt': grpc.unary_unary_rpc_method_handler(
                    servicer.Decrypt,
                    request_deserializer=proto_dot_crypto__pb2.DecryptRequest.FromString,
                    response_serializer=proto_dot_crypto__pb2.DecryptResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'go_webserver.crypto.Crypto', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Crypto(object):
    """Crypto exposes all the necessary RPCs to Encrypt or Decrypt information.
    """

    @staticmethod
    def Encrypt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/go_webserver.crypto.Crypto/Encrypt',
            proto_dot_crypto__pb2.EncryptRequest.SerializeToString,
            proto_dot_crypto__pb2.EncryptResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Decrypt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/go_webserver.crypto.Crypto/Decrypt',
            proto_dot_crypto__pb2.DecryptRequest.SerializeToString,
            proto_dot_crypto__pb2.DecryptResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
